security:
    encoders:
        App\Entity\User:
            algorithm: argon2i

    providers:
        app_user_provider:
            id: App\Security\UserProvider
    firewalls:
        login:
            pattern:  ^/auth
            stateless: true
            anonymous: true
            provider: app_user_provider
            json_login:
                check_path: /auth/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure  
        main:
            pattern:   ^/api
            provider: app_user_provider
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/auth, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/docs, role: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api, roles: ROLE_USER }

