old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    producers:
        # use 'old_sound_rabbit_mq.task_producer' service to send data.
        media:
            connection:       default
            exchange_options: { name: 'media', type: fanout }
            queue_options: { name: 'media'}
        api:
            connection:       default
            exchange_options: { name: '%env(MEDIA_APP_EXCHANGE)%', type: '%env(MEDIA_APP_EXCHANGE_TYPE)%' }
    consumers:
        media:
            connection:       default
#            exchange_options: { name: 'media', type: topic }
            queue_options: { name: 'media'}
            callback:         App\Consumer\MediaConsumer
